---
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

# Treinamento em Programação no Ambiente R

---

`LOCAL`: Departamento de Genética, sala “Marcílio Dias” – ESALQ-USP

`PERÍODO`: 16, 18 e 20 de março de 2020

`VALOR`: Pague quanto quiser/puder (sugestão de R$25,00)

`REALIZAÇÃO`: GENt e Gfito-LQ

`APOIO`: ESALQ, Departamento de Genética, grupo Gfito-LQ 

`PÚBLICO-ALVO`: Estudantes de graduação e pós-graduação.

`PRÉ-REQUISITOS`: Interesse no aprendizado de uma linguagem de programação aplicada à análise de dados.

`IMPORTANTE`: Para aqueles que acompanharão presencialmente, é necessário trazer computador pessoal.

---

## Dia 1 – 16/03
`Horário`:  8h ao 12h

* Familiarização com a interface do RStudio

* Uso do RStudio e linguagem markdown para gerar relatórios

* Operações básicas

* Tipos de objetos


## Dia 2 – 18/03
`Horário`: 8h ao 12h 

* Exportação e importação de dados

* Estruturas condicionais

* Estruturas de repetição

* Elaboração de funções
	
## Dia 3 – 20/03
`Horário`: 8h ao 12h

* Elaboração de gráficos simples

* Instalação e aplicação de pacotes

* Ferramentas básicas de análise de dados
